package assignmentgui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class CatalogueForm extends javax.swing.JFrame {
    
    private static int count;
    private static String header=" MY SHOPPING CART\n\n";
    

    /**
     * Creates new form CatalogueForm
     */
    public CatalogueForm() {
        initComponents();
        
        type.setVisible(false);
        small.setSelected(true);
        small.setVisible(false);
        medium.setSelected(false);
        medium.setVisible(false);
        large.setSelected(false);
        large.setVisible(false);
        aButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capacityGrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        categoryText = new javax.swing.JTextField();
        sButton = new javax.swing.JButton();
        success = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        capacityLabel = new javax.swing.JLabel();
        small = new javax.swing.JRadioButton();
        medium = new javax.swing.JRadioButton();
        large = new javax.swing.JRadioButton();
        gPrice = new javax.swing.JLabel();
        aButton = new javax.swing.JButton();
        added = new javax.swing.JLabel();
        myShoppingCart = new javax.swing.JTextArea();
        logoutLabel = new javax.swing.JLabel();
        cButton = new javax.swing.JButton();

        capacityGrp.add(small);
        capacityGrp.add(medium);
        capacityGrp.add(large);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogue");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CATALOGUE");

        categoryLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoryLabel.setText("Category");

        sButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sButton.setText("Search");
        sButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });

        success.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        success.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        typeLabel.setBackground(new java.awt.Color(204, 204, 255));
        typeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        type.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classic Electric Rice Cooker", "Gas Rice Cooker", "Micro-computerized Rice Cooker" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        capacityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        small.setBackground(new java.awt.Color(204, 204, 255));
        small.setText("Small");
        small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallActionPerformed(evt);
            }
        });

        medium.setBackground(new java.awt.Color(204, 204, 255));
        medium.setText("Medium");
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });

        large.setBackground(new java.awt.Color(204, 204, 255));
        large.setText("Large");
        large.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeActionPerformed(evt);
            }
        });

        gPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        aButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aButton.setText("Add to Cart");
        aButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });

        added.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        added.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        myShoppingCart.setColumns(20);
        myShoppingCart.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        myShoppingCart.setRows(5);
        myShoppingCart.setText(" MY SHOPPING CART\n \n Total Items: 0");

        logoutLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(0, 0, 204));
        logoutLabel.setText("<HTML><U>Logout</U></HTML>");
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        cButton.setText("Clear");
        cButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(myShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(gPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(capacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(small, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(medium, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(large, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(categoryText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(sButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(added, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 74, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(aButton)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(categoryLabel)
                        .addComponent(categoryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(sButton)
                    .addGap(18, 18, 18)
                    .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(small)
                        .addComponent(medium)
                        .addComponent(large)
                        .addComponent(capacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addComponent(gPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(61, 61, 61)
                    .addComponent(added, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(114, Short.MAX_VALUE)))
        );

        capacityLabel.getAccessibleContext().setAccessibleName("Capacity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        // TODO add your handling code here:
        String category = categoryText.getText();
        
        if(category.equals("Rice Cooker")){
            success.setText("Category Found!");
            typeLabel.setText("Type");
            type.setVisible(true);
            capacityLabel.setText("Capacity");
            small.setVisible(true);
            medium.setVisible(true);
            large.setVisible(true);

            if(type.getSelectedIndex()==0 && small.isSelected()==true){
                gPrice.setText("Price: RM 81.00");
            }else if(type.getSelectedIndex()==0 && medium.isSelected()==true){
                gPrice.setText("Price: RM 119.99");
            }else if(type.getSelectedIndex()==0 && large.isSelected()==true){
                gPrice.setText("Price: RM 142.00");
            }else if(type.getSelectedIndex()==1 && small.isSelected()==true){
                gPrice.setText("Price: RM 399.99");
            }else if(type.getSelectedIndex()==1 && medium.isSelected()==true){
                gPrice.setText("Price: RM 479.90");
            }else if(type.getSelectedIndex()==1 && large.isSelected()==true){
                gPrice.setText("Price: RM 622.00");
            }else if(type.getSelectedIndex()==2 && small.isSelected()==true){
                gPrice.setText("Price: RM 235.00");
            }else if(type.getSelectedIndex()==2 && medium.isSelected()==true){
                gPrice.setText("Price: RM 399.89");
            }else if(type.getSelectedIndex()==2 && large.isSelected()==true){
                gPrice.setText("Price: RM 575.90");
            }

            aButton.setVisible(true);

        }else{
            success.setText("Category NOT Found!");
            typeLabel.setText("");
            type.setVisible(false);
            capacityLabel.setText("");
            small.setVisible(false);
            medium.setVisible(false);
            large.setVisible(false);
            gPrice.setText("");
            aButton.setVisible(false);
            added.setText("");

        }
        
    }//GEN-LAST:event_sButtonActionPerformed

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==aButton){
            added.setText("Item Added to Cart Successfully!");
            count++;
            myShoppingCart.setText(header + " Total items: " +count);
        }else{
            added.setText("");
        }        
    }//GEN-LAST:event_aButtonActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
        if(type.getSelectedIndex()==0 && small.isSelected()==true){
            gPrice.setText("Price: RM 81.00");
        }else if(type.getSelectedIndex()==0 && medium.isSelected()==true){
            gPrice.setText("Price: RM 119.99");
        }else if(type.getSelectedIndex()==0 && large.isSelected()==true){
            gPrice.setText("Price: RM 142.00");
        }else if(type.getSelectedIndex()==1 && small.isSelected()==true){
            gPrice.setText("Price: RM 399.99");
        }else if(type.getSelectedIndex()==1 && medium.isSelected()==true){
            gPrice.setText("Price: RM 479.90");
        }else if(type.getSelectedIndex()==1 && large.isSelected()==true){
            gPrice.setText("Price: RM 622.00");
        }else if(type.getSelectedIndex()==2 && small.isSelected()==true){
            gPrice.setText("Price: RM 235.00");
        }else if(type.getSelectedIndex()==2 && medium.isSelected()==true){
            gPrice.setText("Price: RM 399.89");
        }else if(type.getSelectedIndex()==2 && large.isSelected()==true){
            gPrice.setText("Price: RM 575.90");
        }        
    }//GEN-LAST:event_typeActionPerformed

    private void smallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallActionPerformed
        // TODO add your handling code here:
        if(type.getSelectedIndex()==0 && small.isSelected()==true){
            gPrice.setText("Price: RM 81.00");
        }else if(type.getSelectedIndex()==1 && small.isSelected()==true){
            gPrice.setText("Price: RM 399.99");
        }else if(type.getSelectedIndex()==2 && small.isSelected()==true){
            gPrice.setText("Price: RM 235.00");
        }
    }//GEN-LAST:event_smallActionPerformed

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed
        // TODO add your handling code here:
        if(type.getSelectedIndex()==0 && medium.isSelected()==true){
            gPrice.setText("Price: RM 119.99");
        }else if(type.getSelectedIndex()==1 && medium.isSelected()==true){
            gPrice.setText("Price: RM 479.90");
        }else if(type.getSelectedIndex()==2 && medium.isSelected()==true){
            gPrice.setText("Price: RM 399.89");
        }
    }//GEN-LAST:event_mediumActionPerformed

    private void largeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeActionPerformed
        // TODO add your handling code here:
        if(type.getSelectedIndex()==0 && large.isSelected()==true){
            gPrice.setText("Price: RM 142.00");
        }else if(type.getSelectedIndex()==1 && large.isSelected()==true){
            gPrice.setText("Price: RM 622.00");
        }else if(type.getSelectedIndex()==2 && large.isSelected()==true){
            gPrice.setText("Price: RM 575.90");
        }
    }//GEN-LAST:event_largeActionPerformed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // TODO add your handling code here:
        count = 0;
        myShoppingCart.setText(header + " Total items: " +count);
        added.setText(null);
    }//GEN-LAST:event_cButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogueForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aButton;
    private javax.swing.JLabel added;
    private javax.swing.JButton cButton;
    private javax.swing.ButtonGroup capacityGrp;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField categoryText;
    private javax.swing.JLabel gPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton large;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JRadioButton medium;
    private javax.swing.JTextArea myShoppingCart;
    private javax.swing.JButton sButton;
    private javax.swing.JRadioButton small;
    private javax.swing.JLabel success;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
